version: '2.1'

services:
  darksky2influxdb:
    image: darksky2influxdb
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 importForecast.js