version: '2.1'

services:
  darksky2influxdb:
    image: darksky2influxdb
    build: .
    environment:
      NODE_ENV: production
    depends_on: 
    - influxdb
  influxdb:
    image: influxdb
    env_file:
    - 'env.influxdb'
    ports:
    - "8086:8086"
  grafana:
    build: './grafana'
    container_name: 'grafana'
    env_file:
    - 'env.grafana'
    ports:
      - '3000:3000'
